# Generated by Django 3.2.5 on 2021-11-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('mobile', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(blank=True, upload_to='img')),
                ('myfile', models.FileField(blank=True, upload_to='doc')),
                ('date', models.DateField()),
            ],
        ),
    ]
