# Generated by Django 3.2.5 on 2021-11-15 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_files',
            name='date',
        ),
    ]
